### ISSUE TITLE
1.5U?

### ISSUE THREAD

**Issue by b166ar** [braindefender/KLP-Lame-Keycaps#1]
Any plans to make 1.5U thumb? For Chocofi and similar keyboards.

**Comment by braindefender** [comment]
No, I do not plan to add 1.5U or other sizes. Perhaps, someone will make PR with this.

**Comment by KLingO-MS** [comment]
Could You please create caps for index center column that will be tilted to the side (of course corner ones then would be tilted in 2 directions)

**Comment by smallwat3r** [comment]
@b166ar I've found a MX version of a 1.5U thumb key on [this](https://github.com/vvhg1/clp-keycaps/blob/main/stl/CLP_Tilt7_1_5u%20v13.stl) repo. The keys have been inspired by the KLP Lame, so it fits quite well the design.

Because I'm using choc keycaps and not MX, I modified it so it has a choc plug, you can find the STL attached.

[CLP_Tilt7_1_5u_choc.stl.zip](https://github.com/braindefender/KLP-Lame-Keycaps/files/15366275/CLP_Tilt7_1_5u_choc.stl.zip)

![Screenshot 2024-05-18 at 18 44 01](https://github.com/braindefender/KLP-Lame-Keycaps/assets/34649606/6b49dd73-a973-406e-80c9-be8dfe3f5b93)

**Comment by braindefender** [comment]
Now there are 1.5 variants
