### ISSUE TITLE
Increase home keys bumps

### ISSUE THREAD

**Issue by mike1808** [braindefender/KLP-Lame-Keycaps#6]
The current version has a very small bumps to indicate home keys. When printed with 50 micron mSLA printer those nibs are very hard to feel. 
I tried increasing the ball diameter to 2mm and only having two of those and it feels good to use. 
<img width="655" alt="image" src="https://github.com/braindefender/KLP-Lame-Keycaps/assets/3942554/27cf673f-849b-411c-b723-95391b41b17f">

I can provide pictures of printed caps if needed.

**Comment by ald0o** [comment]
I printed them in FDM (TPU 95A) "super quality" (0.12 mm layers... so that would be 120 μm, comparing apples to apples!), and the bumps are also completely unnoticeable, as expected.

I am aware these keycaps were not meant for FDM, but except the issue with homing bumps, they are actually quite fine, so it would definitely be worth it to fix this little issue.

**Comment by mike1808** [comment]
I tried making a photo but not sure you can see it. On the left is my modified version, on the right is the original version 
![image](https://github.com/braindefender/KLP-Lame-Keycaps/assets/3942554/dab55fc7-1c1a-45b3-8c78-6206577dab33)

**Comment by braindefender** [comment]
I'll fix it in the next update

**Comment by braindefender** [comment]
You are welcome. Check out last commits and updates.

**Comment by smallwat3r** [comment]
@mike1808, I quite like your version of the home keys with the increased two dots. Any chance you could share an STL file? Thanks!
